export const data = {
    "timetable": [
        [
            {
                "moduleCode": "COMP1711",
                "moduleTitle": "Procedural Programming",
                "type": "Lecture 1",
                "location": "Roger Stevens LT 22 (10M.22)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "10:00",
                "startPeriod": 20,
                "end": "11:00",
                "endPeriod": 22,
                "weeks": "1-4, 6-11",
                "staff": "Alsalka,Mohammad Ammar,Dr",
                "recording": "1"
            },
            {
                "moduleCode": "COMP1711",
                "moduleTitle": "Procedural Programming",
                "type": "Lab Class 1",
                "location": "EC Stoner Cluster (6.68);EC Stoner Cluster (6.61)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "15:00",
                "startPeriod": 30,
                "end": "17:00",
                "endPeriod": 34,
                "weeks": "1-4, 6-11",
                "staff": "Alsalka,Mohammad Ammar,Dr",
                "recording": "3"
            }
        ],
        [
            {
                "moduleCode": "COMP Tutorial",
                "moduleTitle": "",
                "type": "Tutorial 1",
                "location": "",
                "info1": "",
                "info2": "Weekly Meetings in the Tutors office",
                "info3": "",
                "start": "11:00",
                "startPeriod": 22,
                "end": "12:00",
                "endPeriod": 24,
                "weeks": "1-4, 6-11",
                "staff": "Wang,Zheng,Dr;Wang,He,Dr;Dogar,Mehmet,Dr;Adler,Isolde,Dr;Leonetti,Matteo,Dr;Alsalka,Mohammad Ammar,Dr;Cohen,Netta,Prof;Head,David,Dr;Dimitrova,Vania,Dr;de Kamps,Marc,Dr;McEvoy,Kevin,Dr;Walkley,Mark,Dr;Kwan,Raymond,Dr;Efford,Nicholas,Dr;Bulpitt,Andrew,Dr;Bennett,Brandon,Dr;Ruddle,Roy,Prof;Chakhlevitch,Natalia,Dr;Atwell,Eric,Dr;Duggleby,Gillian;Djemame,Karim,Dr;Muller,Haiko,Dr;Vuskovic,Kristina,Prof;Stell,John,Dr;Johnson,Owen;Xu,Jie,Prof;Carr,Hamish,Dr;Wilson,Sam;Shao,Tianjia,Dr;Lassila,Toni,Dr;Kelly,Thomas,Dr;Gooya,Ali,Dr;Lowe,Amy,Dr",
                "recording": "3"
            },
            {
                "moduleCode": "COMP1211",
                "moduleTitle": "Computer Architecture",
                "type": "Lecture 1",
                "location": "Roger Stevens LT 21 (8M.21)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "12:00",
                "startPeriod": 24,
                "end": "13:00",
                "endPeriod": 26,
                "weeks": "1-4, 6-11",
                "staff": "Wang,Zheng,Dr;McEvoy,Kevin,Dr",
                "recording": "1"
            },
            {
                "moduleCode": "COMP1421",
                "moduleTitle": "Fundamental Math Concepts",
                "type": "Drop-in session",
                "location": "",
                "info1": "",
                "info2": "Venue: The Long Room;  Optional - Attendance Is Not Compulsory",
                "info3": "",
                "start": "13:00",
                "startPeriod": 26,
                "end": "14:00",
                "endPeriod": 28,
                "weeks": "2-4, 6-11",
                "staff": "Wilson,Sam;Adler,Isolde,Dr",
                "recording": "3"
            },
            {
                "moduleCode": "LUBS1170",
                "moduleTitle": "Introduction to Management 1",
                "type": "Lecture 1",
                "location": "Chemical and Process Engineering LT A (2.23)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "16:00",
                "startPeriod": 32,
                "end": "17:00",
                "endPeriod": 34,
                "weeks": "1-11",
                "staff": "Townend,Jo",
                "recording": "2"
            }
        ],
        [
            {
                "moduleCode": "COMP1911",
                "moduleTitle": "Professional Computing",
                "type": "Lecture 1",
                "location": "Roger Stevens LT 22 (10M.22)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "9:00",
                "startPeriod": 18,
                "end": "10:00",
                "endPeriod": 20,
                "weeks": "1-4, 6-11",
                "staff": "Duggleby,Gillian",
                "recording": "1"
            },
            {
                "moduleCode": "COMP1211",
                "moduleTitle": "Computer Architecture",
                "type": "Lecture 2",
                "location": "Roger Stevens LT 22 (10M.22)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "10:00",
                "startPeriod": 20,
                "end": "11:00",
                "endPeriod": 22,
                "weeks": "1-4, 6-11",
                "staff": "Wang,Zheng,Dr;McEvoy,Kevin,Dr",
                "recording": "1"
            },
            {
                "moduleCode": "COMP1421",
                "moduleTitle": "Fundamental Math Concepts",
                "type": "Lecture 1",
                "location": "Roger Stevens LT 22 (10M.22)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "11:00",
                "startPeriod": 22,
                "end": "12:00",
                "endPeriod": 24,
                "weeks": "1-4, 6-11",
                "staff": "Adler,Isolde,Dr",
                "recording": "1"
            },
            {
                "moduleCode": "COMP Level 1 Employability",
                "moduleTitle": "",
                "type": "Lecture 1",
                "location": "Chemical and Process Engineering LT A (2.23)",
                "info1": "",
                "info2": "Employability Introduction",
                "info3": "",
                "start": "12:00",
                "startPeriod": 24,
                "end": "13:00",
                "endPeriod": 26,
                "weeks": "2",
                "staff": "",
                "recording": "1"
            }
        ],
        [
            {
                "moduleCode": "COMP1421",
                "moduleTitle": "Fundamental Math Concepts",
                "type": "Lecture 2",
                "location": "Roger Stevens LT 22 (10M.22)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "9:00",
                "startPeriod": 18,
                "end": "10:00",
                "endPeriod": 20,
                "weeks": "1-4, 6-11",
                "staff": "Adler,Isolde,Dr",
                "recording": "1"
            },
            {
                "moduleCode": "COMP1421",
                "moduleTitle": "Fundamental Math Concepts",
                "type": "Examples Class 1",
                "location": "Roger Stevens LT 22 (10M.22)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "10:00",
                "startPeriod": 20,
                "end": "11:00",
                "endPeriod": 22,
                "weeks": "1-4, 6-11",
                "staff": "Adler,Isolde,Dr",
                "recording": "1"
            },
            {
                "moduleCode": "COMP1421",
                "moduleTitle": "Fundamental Math Concepts",
                "type": "Drop-in session",
                "location": "",
                "info1": "",
                "info2": "Venue: The Long Room;  Optional - Attendance Is Not Compulsory",
                "info3": "",
                "start": "11:00",
                "startPeriod": 22,
                "end": "12:00",
                "endPeriod": 24,
                "weeks": "2-4, 6-11",
                "staff": "Wilson,Sam;Adler,Isolde,Dr",
                "recording": "3"
            },
            {
                "moduleCode": "COMP1421",
                "moduleTitle": "Fundamental Math Concepts",
                "type": "Seminar 1",
                "location": "Parkinson SR (B.08)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "15:00",
                "startPeriod": 30,
                "end": "16:00",
                "endPeriod": 32,
                "weeks": "2-4, 6-11",
                "staff": "Adler,Isolde,Dr",
                "recording": "3"
            }
        ],
        [
            {
                "moduleCode": "COMP1911",
                "moduleTitle": "Professional Computing",
                "type": "Lecture 2",
                "location": "Roger Stevens LT 22 (10M.22)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "9:00",
                "startPeriod": 18,
                "end": "10:00",
                "endPeriod": 20,
                "weeks": "1-4, 6-11",
                "staff": "Duggleby,Gillian",
                "recording": "1"
            },
            {
                "moduleCode": "COMP1711",
                "moduleTitle": "Procedural Programming",
                "type": "Lecture 2",
                "location": "Roger Stevens LT 22 (10M.22)",
                "info1": "",
                "info2": "",
                "info3": "",
                "start": "14:00",
                "startPeriod": 28,
                "end": "15:00",
                "endPeriod": 30,
                "weeks": "1-4, 6-11",
                "staff": "Alsalka,Mohammad Ammar,Dr",
                "recording": "1"
            }
        ],
        [],
        []
    ],
    "info": {
        "weekStarting": "07 Oct 2019"
    }
}